apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-mango
  namespace: default
spec:
  project: default

  source:
    repoURL: https://github.com/dario-lab/Kubernetes.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: mango

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
